### ISSUE TITLE
Clojure 1.9 compat

### ISSUE THREAD

**Issue by jcf** [palletops/lein-shorthand#7]
Looks like there's an issue with Clojure 1.9 as of alpha-11 and lein-shorthand. In case this affects anyone else I wanted to create a quick issue.

[`com.palletops.shorthand/var-fn`](https://github.com/palletops/lein-shorthand/blob/0020e8d1a8a30e596dbd06532c9cb9d37998a5e6/src/com/palletops/shorthand.clj#L13) fails to conform to both `:clojure.core.specs/arg-list` and `:clojure.core.specs/args+body`.

It's possible this is an issue in Clojure rather than lein-shorthand. I haven't had an in-depth look as of yet.

Full stacktrace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Call to clojure.core/fn did not conform to spec:
In: [0] val: com.palletops.shorthand/var-fn fails spec: :clojure.core.specs/arg-list at: [:args :bs :arity-1 :args] predicate: vector?
In: [0] val: com.palletops.shorthand/var-fn fails spec: :clojure.core.specs/args+body at: [:args :bs :arity-n] predicate: (cat :args :clojure.core.specs/arg-list :prepost (? map?) :body (* any?))
:clojure.spec/args  (com.palletops.shorthand/var-fn [ns__635__auto__ sym__636__auto__ v-sym__637__auto__ meta-m__638__auto__] (clojure.core/intern ns__635__auto__ (clojure.core/with-meta sym__636__auto__ (clojure.core/merge {:arglists (quote [[& com.palletops.shorthand/not-yet-loaded]])} meta-m__638__auto__ (clojure.core/meta (clojure.core/resolve v-sym__637__auto__)) (clojure.core/meta sym__636__auto__))) (clojure.core/fn [& args__639__auto__] (clojure.core/let [v-ns__640__auto__ (clojure.core/symbol (clojure.core/namespace v-sym__637__auto__))] (try (clojure.core/require v-ns__640__auto__) (catch java.lang.Exception e__641__auto__ (throw (clojure.core/ex-info (clojure.core/str "Problem loading namespace " v-ns__640__auto__ " for injections:") {:ns ns__635__auto__, :name sym__636__auto__, :var v-sym__637__auto__} e__641__auto__))))) (clojure.core/let [src-v__642__auto__ (clojure.core/resolve v-sym__637__auto__) tgt-v__643__auto__ (clojure.core/resolve (clojure.core/symbol (clojure.core/name ns__635__auto__) (clojure.core/name sym__636__auto__)))] (clojure.core/when-not src-v__642__auto__ (throw (clojure.core/ex-info (clojure.core/str "Failed to inject " v-sym__637__auto__ ". Could not resolve it.") {:ns ns__635__auto__, :name sym__636__auto__, :var v-sym__637__auto__}))) (clojure.core/alter-var-root tgt-v__643__auto__ (clojure.core/constantly src-v__642__auto__)) (clojure.core/alter-meta! tgt-v__643__auto__ clojure.core/merge (clojure.core/dissoc (clojure.core/meta src-v__642__auto__) :name :ns)) (clojure.core/apply (clojure.core/deref src-v__642__auto__) args__639__auto__)))))
, compiling:(/OMITTED/target/fe7c305f738ff1bbced52eac1572271a8f26cfd1-init.clj:1:931)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6795)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6878)
        at clojure.lang.Compiler.analyze(Compiler.java:6674)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6271)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6892)
        at clojure.lang.Compiler.analyze(Compiler.java:6674)
        at clojure.lang.Compiler.analyze(Compiler.java:6630)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6003)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6890)
        at clojure.lang.Compiler.analyze(Compiler.java:6674)
        at clojure.lang.Compiler.eval(Compiler.java:6948)
        at clojure.lang.Compiler.eval(Compiler.java:6940)
        at clojure.lang.Compiler.load(Compiler.java:7403)
        at clojure.lang.Compiler.loadFile(Compiler.java:7341)
        at clojure.main$load_script.invokeStatic(main.clj:276)
        at clojure.main$init_opt.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invoke(main.clj:278)
        at clojure.main$initialize.invokeStatic(main.clj:309)
        at clojure.main$null_opt.invokeStatic(main.clj:343)
        at clojure.main$null_opt.invoke(main.clj:340)
        at clojure.main$main.invokeStatic(main.clj:422)
        at clojure.main$main.doInvoke(main.clj:385)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Call to clojure.core/fn did not conform to spec:
In: [0] val: com.palletops.shorthand/var-fn fails spec: :clojure.core.specs/arg-list at: [:args :bs :arity-1 :args] predicate: vector?
In: [0] val: com.palletops.shorthand/var-fn fails spec: :clojure.core.specs/args+body at: [:args :bs :arity-n] predicate: (cat :args :clojure.core.specs/arg-list :prepost (? map?) :body (* any?))
:clojure.spec/args  (com.palletops.shorthand/var-fn [ns__635__auto__ sym__636__auto__ v-sym__637__auto__ meta-m__638__auto__] (clojure.core/intern ns__635__auto__ (clojure.core/with-meta sym__636__auto__ (clojure.core/merge {:arglists (quote [[& com.palletops.shorthand/not-yet-loaded]])} meta-m__638__auto__ (clojure.core/meta (clojure.core/resolve v-sym__637__auto__)) (clojure.core/meta sym__636__auto__))) (clojure.core/fn [& args__639__auto__] (clojure.core/let [v-ns__640__auto__ (clojure.core/symbol (clojure.core/namespace v-sym__637__auto__))] (try (clojure.core/require v-ns__640__auto__) (catch java.lang.Exception e__641__auto__ (throw (clojure.core/ex-info (clojure.core/str "Problem loading namespace " v-ns__640__auto__ " for injections:") {:ns ns__635__auto__, :name sym__636__auto__, :var v-sym__637__auto__} e__641__auto__))))) (clojure.core/let [src-v__642__auto__ (clojure.core/resolve v-sym__637__auto__) tgt-v__643__auto__ (clojure.core/resolve (clojure.core/symbol (clojure.core/name ns__635__auto__) (clojure.core/name sym__636__auto__)))] (clojure.core/when-not src-v__642__auto__ (throw (clojure.core/ex-info (clojure.core/str "Failed to inject " v-sym__637__auto__ ". Could not resolve it.") {:ns ns__635__auto__, :name sym__636__auto__, :var v-sym__637__auto__}))) (clojure.core/alter-var-root tgt-v__643__auto__ (clojure.core/constantly src-v__642__auto__)) (clojure.core/alter-meta! tgt-v__643__auto__ clojure.core/merge (clojure.core/dissoc (clojure.core/meta src-v__642__auto__) :name :ns)) (clojure.core/apply (clojure.core/deref src-v__642__auto__) args__639__auto__)))))

        at clojure.spec$macroexpand_check.invokeStatic(spec.clj:627)
        at clojure.spec$macroexpand_check.invoke(spec.clj:616)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6789)
        ... 27 more
```

**Comment by gfredericks** [comment]
This has been fixed and released as `[com.gfredericks/lein-shorthand "0.4.1"]` (note the changed group-id).
